name: Run SCF_sign.py

on:
  workflow_dispatch:
  schedule:
    # 每天的 UTC 时间 00:00 运行
    - cron: '1 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run SCF_sign.py
        run: python dist/SCF_sign.py
        env:
          COOKIES: ${{ secrets.COOKIES }}